import googleAds from './google-ads';
import metaAds from './meta-ads';
import tiktokAds from './tiktok-ads';
import amazonAds from './amazon-ads';
import ebayAds from './ebay-ads';
import etsyAds from './etsy-ads';
import microsoftAds from './microsoft-ads';
import linkedinAds from './linkedin-ads';
import youtubeAds from './youtube-ads';
import displayRemarketing from './display-remarketing';
export const pageContent={'google-ads':googleAds,'meta-ads':metaAds,'tiktok-ads':tiktokAds,'amazon-ads':amazonAds,'ebay-ads':ebayAds,'etsy-ads':etsyAds,'microsoft-ads':microsoftAds,'linkedin-ads':linkedinAds,'youtube-ads':youtubeAds,'display-remarketing':displayRemarketing};
