import PlatformHero from '@/components/PlatformHero';
import PlatformExperience from '@/components/PlatformExperience';
import {platforms} from '@/lib/platforms';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {services,siteUrl} from '@/lib/services';
import {CTA,FAQs} from '@/components/PageParts';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)return {};return {title:`${s.name} Management in Islamabad`,description:s.intro,alternates:{canonical:`/services/${s.slug}/`},openGraph:{title:`${s.name} | MrPPC.pk`,description:s.intro}}}
export default async function Service({params}){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();const related=services.filter(x=>x.slug!==s.slug).sort((a,b)=>Number(b.category===s.category)-Number(a.category===s.category)).slice(0,3);const schema={'@context':'https://schema.org','@type':'Service',name:`${s.name} management`,description:s.intro,url:`${siteUrl}/services/${s.slug}/`,provider:{'@type':'Organization',name:'MrPPC.pk'},areaServed:{'@type':'City',name:'Islamabad'}};return <main id="main" className={`platform-page platform-${s.slug}`} style={{'--platform-accent':platforms[s.slug].accent,'--platform-secondary':platforms[s.slug].secondary}}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\u003c')}}/><PlatformHero service={s}/><div className="service-facts"><div className="wrap"><div><span>THE FOCUS</span><strong>{s.focus}</strong></div><div><span>BASED IN</span><strong>Islamabad, Pakistan</strong></div><div><span>LED BY</span><strong>Syed Mudassir Shah</strong></div></div></div><PlatformExperience key={s.slug} slug={s.slug}/><section className="section light" id="included"><div className="wrap"><div className="section-heading reveal"><div><p className="eyebrow">A CONSIDERED CAMPAIGN</p><h2>What your strategy<br/><span>is built on.</span></h2></div><p>{s.audience}</p></div><div className="deliverable-grid">{s.deliverables.map(([title,text],i)=><article className="reveal" key={title}><span className="detail-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="format-list"><strong>Areas we can explore</strong><div>{s.formats.map(f=><span key={f}>{f}</span>)}</div><p>Final scope depends on your goals, account eligibility and available assets.</p></div></div></section><section className="section approach"><div className="wrap"><p className="eyebrow">FROM PLAN TO PROGRESS</p><h2>Your next campaign,<br/><em>step by step.</em></h2><div className="steps">{s.steps.map((text,i)=><article className="reveal" key={text}><span className="step-number">0{i+1}</span><div className="step-track"/><h3>{['Understand','Launch','Improve'][i]}</h3><p>{text}</p></article>)}</div></div></section><section className="section light"><div className="wrap faq-grid"><div><p className="eyebrow">USEFUL TO KNOW</p><h2>Your {s.name}<br/>questions.</h2></div><FAQs items={s.faqs}/></div></section><section className="section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">COMPLETE THE PICTURE</p><h2>Explore related services.</h2></div></div><div className="related-grid">{related.map(r=><Link href={`/services/${r.slug}/`} key={r.slug}><span>{r.category}</span><h3>{r.name}</h3><p>{r.focus}</p></Link>)}</div></div></section><CTA title={`Let’s talk ${s.name}.`} platform={s.name}/></main>}
